FROM arindamchoudhury/hadoop-master:latest

MAINTAINER Arindam Choudhury <arindam@live.com>

WORKDIR /home/hdfs

COPY files/bootstrap.sh /etc/bootstrap.sh
RUN chmod +x /etc/bootstrap.sh

RUN chmod +x /etc/bootstrap.sh