#!/usr/bin/env bash
HADOOP_PREFIX=/usr/local/hadoop-2.7.2
HADOOP_COMMON_HOME=$HADOOP_PREFIX
HADOOP_HDFS_HOME=$HADOOP_PREFIX
HADOOP_MAPRED_HOME=$HADOOP_PREFIX
HADOOP_YARN_HOME=$HADOOP_PREFIX
HADOOP_CONF_DIR=$HADOOP_PREFIX/etc/hadoop
YARN_CONF_DIR=$HADOOP_PREFIX/etc/hadoop
HADOOP_LOG_DIR=/var/log/hadoop/hdfs
YARN_LOG_DIR=/var/log/hadoop/yarn
HADOOP_MAPRED_LOG_DIR=/var/log/hadoop/mapred
PATH=$HADOOP_PREFIX/bin:$HADOOP_PREFIX/sbin:$PATH
export HADOOP_PID_DIR HADOOP_MAPRED_LOG_DIR HADOOP_LOG_DIR YARN_LOG_DIR HADOOP_PREFIX HADOOP_COMMON_HOME HADOOP_HDFS_HOME HADOOP_MAPRED_HOME HADOOP_YARN_HOME HADOOP_CONF_DIR YARN_CONF_DIR PATH